### ISSUE TITLE
Finde das Modul haConfig nicht

### ISSUE THREAD

**Issue by Hankaba** [prigei/boesch-kermi-heatpump#1]
Hallo, ich bin ebenfalls sehr unglücklich darüber, dass ich meine neue Wärmepumpe Mozart entgegen den Versprechungen vor dem Vertragsabschluß jetzt doch nicht in meine ioBroker-Hausautomatisierung einbinden kann. Auf der Suche nach Workarounds bin ich auf dein vielversprechendes Projekt gestoßen. Ich habe mich vor einiger Zeit mal mit Python befasst, aber das meiste wieder vergessen. Deshalb taste ich ich mich jetzt langsam anhand deines Codes an meine eigene Implementierung. Aktuell hänge ich am Objekt haConfig. Kann es sein, dass das im Repository fehlt? Ich habe auch keine MQTT-Client-Konfiguration gefunden. Ich würde mich freuen, wenn du mir ein wenig auf die Sprünge helfen könntest. LG, Achim

**Comment by prigei** [comment]
habe das script etwas angepasst und haConfig ist nun ein json file. somit sollte es nun etwas klarer sein. wenn du das json file anpasst mit den mqtt parametern und bei boesch die homeserverid und deviceid sollte das script laufen

**Comment by Hankaba** [comment]
Jetzt bin ich schon etwas weiter. Vielen Dank! Kann es aber sein, dass die GUIDS für die Datenpunkte variieren? Ich bekomme beim Abruf der read_value_url einen JSONDecodeError (data_points = json.loads(response.text)['ResponseData']). Wie es aussieht, hat die Anmeldung bis zu diesem Punkt aber funktioniert. Wie hast du die GUIDs ermittelt? Hat die Portalumstellung auf die neue Version keinen Einfluss auf dein Skript gehabt? LG, Achim

**Comment by prigei** [comment]
die GUIDs variieren vermutlich. das kann ich natürlich nicht testen mit einer wärmepumpe. die GUIDs bekommst du ebenfalls über inspect im webbrowser. am besten über das statistik logging. bzw auch wenn du einstellungen verändern willst siehst du das auch im netzwerk traffic

**Comment by Hankaba** [comment]
Hallo,Ich hatte das Script mit Hilfe deiner Vorlage und Reverse Engineering der UIDs ein Jahr fehlerfrei am Laufen. Ich konnte beliebige Werte auslesen und ändern. Seit gestern läuft das Skript nicht mehr, weil die Portal-Adresse geändert wurde. Nutzt du dein Skript noch und hast das gleiche Problem?

**Comment by prigei** [comment]
ja, bei mir läufts auch nicht mehr. sehe ich mir heute an.

**Comment by prigei** [comment]
kermi hat die authentifizierung auf JWT umgestellt. war etwas mühsamer als gedacht. läuft jetzt wieder. allerdings habe ich vor einiger zeit bei mir auch die config etwas angepasst. sollte aber nicht allzu schlimm sein.

**Comment by Hankaba** [comment]
Hi, ich versuche gerade deine Lösung für mich zu adaptieren. Allerdings möchte ich das Script gerne auf meinem Raspberry Pi laufen lassen, auf dem auch der ioBroker läuft. Ich komme in der Funktion get_login_csrf_token nicht weiter, weil hier Daten aus der config ausgelesen werden sollen, die dort nicht existieren, z. B. client_id oder redirect_uri. Kannst du mir bitte auf die Sprünge helfen, wo diese Werte herkommen und was dort in der config.json eingetragen werden soll? LG

**Comment by prigei** [comment]
stimmt, da haben ein paar parameter gefehlt, sind jetzt da.

**Comment by Hankaba** [comment]
Jetzt funktioniert mein Monitoring auch wieder. Vielen Dank!

**Comment by prigei** [comment]
jetzt habe ich noch eine frage: welche parameter sind zu aendern, damit es laeuft? nur homeServerId und DeviceId nehme ich an. korrekt?

**Comment by Hankaba** [comment]
Ich musste einiges am Monitoring ändern, denn im Gegensatz zu deiner Implementierung habe ich drei Device-IDs (Wärmepumpe, Heizpuffer und Warmwasser). Deshalb habe ich die Dictionaries (z. B. monitorDatapoints) so geändert, dass die device_id Teil der Daten ist und im Falle von monitorDatapoints meine MQTT-Datenpunktbenennung den Key darstellt:

`"monitorDatapoints": {"Isttemperatur TWE": {"config_id": "06e61673-abc2-4671-9e5a-960809d1f326","device_id": "495a5e3d-d9a6-46e5-a456-4a9a5016886d", "device": "Warmwasser", "type": "float", "unit": "C", "factor": 1 }, ...
`

Das hat natürlich zur Folge, dass in der Implementierung der Zugriff auf Daten der Dictionaries an einigen Stellen geändert werden musste.

Außerdem musste ich die Methode für den Zugriff auf die config.json dahingehend ändern, dass die config aus dem Dateisystem gelesen wird. Ich lasse das Monitoring-Skript boeschCLI.py in einem shell-script über crontab lokal auf meinem RaspberryPi laufen. Ich habe keine Erfahrung mit aws, deshalb war mir die lokale Implementierung ohne boto3 lieber.

Ich habe noch einige andere Kleinigkeiten geändert, z. B. die Value-Prüfung bei Boolean-Werten in setDatapoints. Aber das sind nur Kleinigkeiten. Mir hat deine Vorlage sehr viel geholfen. Vielen Dank dafür!

**Comment by Hankaba** [comment]
Servus, funktioniert deine Steuerung heute morgen noch? Meine endet seit ca. 7:00 mit dem Fehler "Failed to get CSRF token during login. Authentication failed. Exiting." Die Kermi-App verbindet sich. LG

**Comment by Hankaba** [comment]
session.get bringt als response 404

**Comment by prigei** [comment]
kermi hat wieder die authentifizierung ein wenig geändert. geht jetzt wieder

**Comment by Hankaba** [comment]
Seite heute morgen, 6:20 funktioniert der Login nicht mehr. 

`response = self.session.post(
            login_post_url, data=login_data, 
            headers={'Content-Type': 'application/x-www-form-urlencoded', 'Origin': self.config['portal'], 'Referer': response.url},
            allow_redirects=False
        )`

endet mit 401. Auffällig ist, dass dies genau 4 Wochen nach der letzten Änderung passiert. Meinst du, Kermi lässt die Anmeldung nach 4 Wochen verfallen?

LG, Achim

**Comment by prigei** [comment]
nein, das script meldet sich jedesmal neu an. ich schau mir das nächste woche an

**Comment by Hankaba** [comment]
Hallo, läuft das Modul bei dir noch? Oder konntest du inzwischen herausfinden, ob Kermi wieder eine Adresse geändert hat?
LG Achim

**Comment by prigei** [comment]
ja, unverändert. war eine wartung bei kermi
